version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-osdccb
    ports:
      - "9000:9000"  # Port binding
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=${SONAR_DB_USER:-sonar}
      - SONAR_JDBC_PASSWORD=${SONAR_DB_PASSWORD:-sonarpass}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: sonarqube-postgres
    environment:
      - POSTGRES_USER=${SONAR_DB_USER:-sonar}
      - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD:-sonarpass}
      - POSTGRES_DB=sonarqube
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
