version: '3.8'

services:
  osdcloudcustombuilder:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: osdcloud-powershell
    volumes:
      - ..:/workspace:cached
      - osdcloud-modules:C:/Users/ContainerAdministrator/Documents/PowerShell/Modules
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - PSModulePath=C:/workspace/Modules;C:/Program Files/PowerShell/Modules;C:/Program Files/PowerShell/7/Modules;C:/Windows/System32/WindowsPowerShell/v1.0/Modules
      - SHELL=C:/Program Files/PowerShell/7/pwsh.exe
    # Keep container running
    command: ["pwsh", "-Command", "while($true) { Start-Sleep -Seconds 3600 }"]
    networks:
      - osdcloud-network
    mem_limit: 4g
    restart: unless-stopped
    # Windows containers require process isolation
    # Comment this line if using Linux containers
    isolation: process

networks:
  osdcloud-network:
    driver: nat

volumes:
  osdcloud-modules:
