# Docker Compose for OSDCloudCustomBuilder dev container

services:
  osdcloudcustombuilder:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        POWERSHELL_VERSION: ${POWERSHELL_VERSION:-7.3}
        PESTER_VERSION: ${PESTER_VERSION:-5.4.0}
        PSSCRIPTANALYZER_VERSION: ${PSSCRIPTANALYZER_VERSION:-1.21.0}
        THREADJOB_VERSION: ${THREADJOB_VERSION:-2.0.3}
        OSD_VERSION: ${OSD_VERSION:-latest}
        OSDCLOUD_VERSION: ${OSDCLOUD_VERSION:-latest}
        MODULEBUILDER_VERSION: ${MODULEBUILDER_VERSION:-2.0.0}
        POWERSHELLPROTOOLS_VERSION: ${POWERSHELLPROTOOLS_VERSION:-latest}
    container_name: osdcloud-powershell
    volumes:
      - ..:/workspace:cached
      - osdcloud-modules:/Users/ContainerAdministrator/Documents/PowerShell/Modules
      - osdcloud-temp:/Temp
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - "PSModulePath=C:/workspace/Modules;C:/Program Files/PowerShell/Modules;C:/Program Files/PowerShell/7/Modules;C:/Users/ContainerAdministrator/Documents/PowerShell/Modules"
    isolation: ${ISOLATION:-process}
    security_opt:
      - seccomp:unconfined
      - credentialspec:Admin
    platform: windows
    mem_limit: ${CONTAINER_MEMORY:-4g}

volumes:
  osdcloud-modules:
  osdcloud-temp:
