name: PowerShell Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Required PowerShell Modules
      run: |
        pwsh -c "Install-Module PSScriptAnalyzer -Force -Scope CurrentUser"
        pwsh -c "Install-Module Pester -Force -Scope CurrentUser"

    - name: Run PSScriptAnalyzer
      run: |
        pwsh -c "Invoke-ScriptAnalyzer -Path ./ -Recurse -Settings ./PSScriptAnalyzer.settings.psd1"

    - name: Run Tests
      run: |
        pwsh -c "Invoke-Pester -Path ./tests -Output Detailed"
